#spring
spring:
  datasource:                   #mysql
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/gtoa?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    hikari:
      max-lifetime: 500000
  jackson:                     #时间格式化
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0KB
      max-file-size: 500MB
      max-request-size: 500MB
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
#mybatis配置逻辑删除
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    call-setters-on-nulls: true   #配置返回结果集为空时仍返回字段

#fastDFS配置
FastDFS:
  imgPrefixPath: http://120.27.244.176/
  propertiesPath: /D:/config/fastdfs.properties

#oss配置
Oos:
  accessKeyId: LTAI4FoAmdJuwmE5Q6RHffBc
  accessKeySecret: pMWwp6eiqGrnPTYqk2aHn8Q4AVheTs
  bucketName: idse-oss
  endpoint: oss-cn-hangzhou.aliyuncs.com
  filedir: image/

nginx:
  filePath: /file/
  filePathForDownload: /file/download/
  ipAndPortAndFilePrefix: 120.27.244.176:8000/file/

#shiro配置
shiro:
  session-timeout: 86400000 #1天
  session-id-cookie: MES_PLUS_COOKIE
zhaoIpAndPort: 192.168.50.97:8090